apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "*/4 * * * *"
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: bash
              command: ["echo",  "See You There!"]
          restartPolicy: OnFailure