apiVersion: v1
kind: Pod
metadata:
 name: gitrepo
spec:
 containers:
 - image: ubuntu
   name: ubuntu
   command:
   - sleep
   - "3600"
   volumeMounts:
   - mountPath: /app
     name: app-git
 volumes:
 - name: app-git
   gitRepo:
    repository: "https://github.com/Vishwanath-GitHub/Kubernetes-Assignment.git"
